### ISSUE TITLE
Optional argument `mostRecent` for 2D Checkers 

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#295]
Boolean argument (default false) to select the most recent verb of each component axis instead of their sum. Useful for individuated directional keys (eg. WASD, arrows keys, JoyCon D-Buttons) as well as alternate binds where directional input may benefit from taking the last-pressed value while multiple sources are held.

When true, holding left, then depressing and releasing right will give "left right left" instead of "left none left".

**Comment by JujuAdams** [comment]
👍

**Comment by offalynne** [comment]
would you mind updating `obj_test_2d` in dev to 5.0 style at yr convenience to kick me off ? :-]

**Comment by JujuAdams** [comment]
Done!

**Comment by offalynne** [comment]
thanks ! stuff seems broken on 2022.500.0.88, feel free to ping here if you update to a later beta otherwise i'll rollback and author a fix in a little while

**Comment by offalynne** [comment]
Looks like we're on the same beta now but still broken/needs review

**Comment by offalynne** [comment]
#334
